package domain

// TravelRequest describes the user's route-planning intent.
type TravelRequest struct {
	ID               string   `json:"id"`
	DepartureCity    string   `json:"departure_city"`
	DestinationCity  string   `json:"destination_city"`
	Days             int      `json:"days"`
	Budget           float64  `json:"budget"`
	Interests        []string `json:"interests"`
	Travelers        int      `json:"travelers"`
	DateRange        string   `json:"date_range"`
	TransportMode    string   `json:"transport_mode"`
	Pace             string   `json:"pace"`
	WalkingTolerance string   `json:"walking_tolerance"`
	HotelArea        string   `json:"hotel_area"`
	MustVisit        []string `json:"must_visit"`
	Avoid            []string `json:"avoid"`
	TravelerType     string   `json:"traveler_type"`
	BudgetType       string   `json:"budget_type"`
	BudgetIncludes   []string `json:"budget_includes"`
}

// TravelPlan is the structured itinerary generated by a planner.
type TravelPlan struct {
	Title    string       `json:"title"`
	Summary  string       `json:"summary"`
	Days     []TravelDay  `json:"days"`
	Budget   TravelBudget `json:"budget"`
	Warnings []string     `json:"warnings"`
}

// TravelDay contains the plan for one travel day.
type TravelDay struct {
	Day   int          `json:"day"`
	Theme string       `json:"theme"`
	Items []TravelItem `json:"items"`
}

// TravelItem describes one scheduled activity or transport segment.
type TravelItem struct {
	Time            string  `json:"time"`
	Type            string  `json:"type"`
	Name            string  `json:"name"`
	Address         string  `json:"address"`
	Reason          string  `json:"reason"`
	EstimatedCost   float64 `json:"estimated_cost"`
	DurationMinutes int     `json:"duration_minutes"`
}

// TravelBudget breaks down the estimated route cost.
type TravelBudget struct {
	Transport float64 `json:"transport"`
	Food      float64 `json:"food"`
	Hotel     float64 `json:"hotel"`
	Ticket    float64 `json:"ticket"`
	Total     float64 `json:"total"`
}
